- name: Set architecture facts
  ansible.builtin.set_fact:
    is_amd64: "{{ ansible_facts.architecture == 'x86_64' }}"
    is_arm64: "{{ ansible_facts.architecture == 'aarch64' or ansible_facts.architecture == 'arm64' }}"
  tags: always
