- name: Get GPG key fingerprint
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "user.name", value: "{{ configure_git_user_name }}" }
    - { name: "user.email", value: "{{ configure_git_user_email }}" }
    - { name: "gpg.program", value: "gpg" }
    - { name: "commit.gpgsign", value: "true" }
    - { name: "user.signingkey", value: "{{ configure_git_gpg_fingerprint.stdout }}" }
